title: 用 Quarto 写作中文学术论文
subtitle: 一个简单的示例
author:
  name: Tom Ben
  email: email@example.edu
student-id: 1234567890
supervisor: 导师姓名
institute: 所在学校名称
major: 专业名称
date-format: "YYYY年M月D日"
date: today
date-modified: today
project:
  output-dir: outputs
number-sections: true
link-citations: true
toc: true
toc-depth: 4  # `3` is enough, `4` is set as `shift-heading-level-by: 1` is enabled for html
toc-title: 目录
crossref:
  fig-title: 图
  tbl-title: 表
  fig-prefix: 图
  tbl-prefix: 表
reference-section-title: 参考文献
bibliography: bibliography.json
csl: _styles/gb-author-date.csl
nocite: |
  @*
filters:
  - links-to-citations
  - ignore-softbreaks
  - text-align
  - custom-fonts
  - sort-citations
execute:
  cache: true
  freeze: auto
  echo: true
  warning: false
fig-dpi: 300

format:
  docx:
    reference-doc: _styles/custom.docx
    template: _styles/custom.openxml
    filters:
      - remove-spaces
      - docx-quotes
      - no-first-paragraph

  html:
    template: _styles/html5.html
    date: 2024-05-26
    theme:
      light: [flatly, _styles/custom.scss]
      dark: [darkly, _styles/custom.scss]
    shift-heading-level-by: 1
    title-block-style: manuscript
    title-block-banner: true
    link-external-icon: true
    link-external-newwindow: true
    lightbox: true
    language:
      title-block-author-single: 作者
      title-block-affiliation-single: 学校
      title-block-published: 发布于
      title-block-modified: 更新于
      section-title-footnotes: 脚注
      related-formats-title: 其他格式
    include-in-header: _styles/citation-order.html

  epub:
    epub-cover-image: figures/cover.png
    rights: © 2025 Tom Ben

  typst:
    output-file: typst
    template: _styles/custom.typst
    filters:
      - typst-quotes
    citeproc: true
    knitr:
      opts_chunk:
        dev: "png"
    mainfont: Times New Roman
    covers: latin-in-cjk
    mainfontfallback:
      - SimSun
      - FangSong
    # codefont: JetBrains Mono
    fontsize: 12pt
    papersize: a4
    linestretch: 1.5
    section-numbering: 1.1.1
    margin:
      top: 2.5cm
      bottom: 2.5cm
      left: 2.5cm
      right: 2.5cm
    linkcolor: "#1A73E8" # Google Blue for external links
    citecolor: "#4B6FA8" # Slate Blue for citations
    filecolor: "#800000" # Wine Red for cross references
    # keep-typ: true

  pdf:
    filters:
      - latex-body-quotes
      - latex-header-quotes
    include-in-header:
      - _styles/custom.tex
    template-partials:
      - _styles/hypersetup.latex
      - _styles/title.tex
      - _styles/before-body.tex
      - _styles/toc.tex
    pdf-engine: xelatex  # The default engine has been changed to `lualatex` since Quarto 1.8.10
    indent: true
    papersize: a4
    twoside: true
    geometry: [margin=2.5cm]
    linkcolor: winered
    citecolor: winered
    urlcolor: urlblue
    toccolor: wordblue
    # keep-tex: true

  revealjs:
    template: _styles/revealjs.html
    theme: _styles/metropolis.scss
    output-file: slides.html
    logo: figures/logo.svg
    citeproc: false
    toc-depth: 1
    menu: false
    scrollable: true
    slide-number: true
    number-sections: false
    chalkboard:
      buttons: false
    pdf-separate-fragments: true
    include-in-header:
      - text: |
          <style>
          .reveal .slide-logo {
            max-height: unset;
            height: 50px;
          }
          </style>
    revealjs-plugins:
      - confetti
